services:
  db:
    image: postgres:16-alpine
    container_name: edunext-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - edunext-network

  app:
    build: .
    container_name: edunext-api
    restart: always
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: ${PGDATABASE}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PORT: 8080
      
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    ports:
      - "8080:8080"
    networks:
      - edunext-network

volumes:
  postgres_data:

networks:
  edunext-network:
    driver: bridge